name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.x

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Restore dependencies
        run: |
          just setup
          just restore

      #- name: Check formatting
      #  run: just format-check

      - name: Build
        run: just build
